### ISSUE TITLE
Need fav Icon

### ISSUE THREAD

**Issue by Lablnet** [zestframework/Zest#43]
Currently we used Logo in case of fav icon too

![image](https://user-images.githubusercontent.com/27757785/65784568-cbe45580-e16b-11e9-8ccf-f5ce622ba74e.png)

Look this, and i think we just need the highlighted area for fav icon

Thanks

**Comment by dovy** [comment]
Do you have a vector of this?

**Comment by dovy** [comment]
See pull #44

**Comment by dovy** [comment]
And please assign to me.  :P

**Comment by Lablnet** [comment]
> Do you have a vector of this?

Nope, but you do good work

**Comment by dovy** [comment]
Thanks. You might consider handing the png I made to a designer and having them recreate it in vector form. Either way the favicon is pretty close to what you’d do. ;)
